name: Create/update tag
on:
  workflow_dispatch:
    
jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: v0.0.1
          message: "Version 0.0.1"
          token: ${{ secrets.GITHUB_TOKEN }}
