name: Create/update tag
on:
  workflow_dispatch:
    
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "0.1"
          tag_exists_error: false
          message: "0.1 release"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Print result using the env variable.
      -  run: |
          echo "Tag already present: ${{ env.TAG_EXISTS }}"
