name: Create/update tag
on:
  workflow_dispatch:
    
jobs:
  create-tag:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: 1.0
          message: "Version 1.0"
          token: ${{ secrets.GITHUB_TOKEN }}
